from playwright.sync_api import sync_playwright
import json
from bs4 import BeautifulSoup
import re
from datetime import datetime



with open("Data/sources.json", "r") as file:
    data=json.load(file)

#print(data)

#response = requests.get(data["weather-gov-home"]["site"])

city = "Houston"
state = "TX"

def get_weather_html(browser, city, state):

    page = browser.new_page()
    page.goto(data["weather-gov-home"]["site"])
    input_box = page.locator(data["weather-gov-home"]["input-box-CSS-Selector"])
    input_box.fill(f"{city}, {state}")
    input_box.press("Enter")

    page.wait_for_load_state("networkidle")    
    search_btn = page.locator(data["weather-gov-home"]["input-box-button-CSS-Selector"])

    search_btn.click()

    unwanted_elements = [".moreInfo",    
                         "#localWFO",
                         "#moreWx",
                         r"#\33 dayHist",
                         "#wxGraph"]
    for css_selector in unwanted_elements:
        page.locator(css_selector).evaluate("element => element.remove()")
    summary_element = page.locator(data["weather-gov-home"]["weather-redirect-page-summary-CSS-Selector"])
    #page.close()
    return summary_element.inner_html()

def get_moon_html(browser):
    page = browser.new_page()
    page.goto(data["moongiant"]["site"] + "/" + data["moongiant"]["phase-page"])
    summary_element = page.locator(data["moongiant"]["phase-summary-CSS-Selector"])
    #page.close()
    return summary_element.inner_html()


def get_data():
    content_html = ""

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        weather_html = get_weather_html(browser, city, state)
        moon_html = get_moon_html(browser)
        content_html = weather_html + moon_html
        #print(content_html)
        with open("Data/unstructured_dataset.html", "w") as f:
            soup = BeautifulSoup(content_html, "html.parser")
            raw_html = str(soup.prettify())
            f.write(raw_html)
        browser.close()

def get_key_vals_from_table(soup, processed_table):

    #soup.div.unwrap()
    #print(soup)
    table_rows = soup.find_all("tr")
    table = {}
    i = 0
    for row in table_rows:
        table_datas = row.find_all("td")
        table_row = []
        for data in table_datas:
            text = data.text
            text = re.sub(r"\s{2,}", "", text, re.X | re.I)
            table_row.append(text)
            data.decompose()
        table[i] = table_row
        i += 1

    for row_num, row_contents in table.items():
        if len(row_contents) > 1:
            key = row_contents[0]
            value = "".join(row_contents[1:])
            processed_table[key] = value
        elif len(row_contents) == 1:
            key = row_contents[0]
            processed_table[key] = None

    soup = BeautifulSoup(re.sub(r"\s{2,}", "", str(soup), re.X | re.I), "html.parser")
    return soup
def get_data_from_pattern(soup, processed_table, pattern):
    hits = pattern.findall(str(soup))
    for hit in hits:
        key, value = hit
        processed_table[key] = value
    return

from html import escape


def dict_to_html_table(data: dict, title: str | None = None) -> str:
    """
    disclaimer: the following html was generated by Chat-GPT
    """
    rows = ""

    for key, value in data.items():
        rows += f"""
        <tr>
            <td class="key">{escape(str(key))}</td>
            <td class="value">{escape(str(value))}</td>
        </tr>
        """

    title_html = f"<h2>{escape(title)}</h2>" if title else ""

    return f"""
    <div class="table-container">
        {title_html}

        <table>
            <thead>
                <tr>
                    <th>Property</th>
                    <th>Value</th>
                </tr>
            </thead>

            <tbody>
                {rows}
            </tbody>
        </table>
    </div>

    <style>
        .table-container {{
            font-family: Arial, sans-serif;
            max-width: 700px;
            margin: 20px auto;
        }}

        .table-container h2 {{
            text-align: center;
            margin-bottom: 12px;
        }}

        table {{
            width: 100%;
            border-collapse: collapse;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
        }}

        th {{
            background-color: #333;
            color: white;
            padding: 12px;
            text-align: left;
        }}

        td {{
            padding: 10px 12px;
            border-bottom: 1px solid #ddd;
        }}

        tbody tr:nth-child(even) {{
            background-color: #f5f5f5;
        }}

        tbody tr:hover {{
            background-color: #e8e8e8;
        }}

        .key {{
            font-weight: bold;
            width: 40%;
        }}

        .value {{
            width: 60%;
        }}
    </style>
    """

if __name__ == "__main__":

    get_data()

    content_html = ""
    with open("Data/unstructured_dataset.html", "r") as file:
        content_html = "\n".join(file.readlines())
    processed_table = {}
    soup = BeautifulSoup(content_html, "html.parser")
    for br in soup.find_all("br"):
        br.replace_with("\n")
    #print(soup.prettify())
    soup = get_key_vals_from_table(soup, processed_table)
    pattern = re.compile(r"(?P<key>[\w\s]+):\s*<span>(?P<value>[^<]+)</span>",flags=re.I | re.X | re.DOTALL)
    #print(pattern.findall(str(soup)))
    #print(str(soup))
    get_data_from_pattern(soup, processed_table, pattern)
    now = datetime.now()
    #17:45:34.579237
    formatted_date = now.strftime("%Y-%m-%d")
    processed_html_data = dict_to_html_table(processed_table, f"Weather ({city}, {state}) and Moon Data for {formatted_date}")
    with open("Data/processed_data.html", "w") as f:
        f.write(processed_html_data)

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        page = browser.new_page()
        page.set_content(processed_html_data)
        page.wait_for_event("close")
